#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "open3"
require "pathname"

# Build-time data only: the published page does not call the GitHub API.
module LatestChanges
  LIMIT = 10
  OUTPUT = "includes/_latest-changes.md"
  REPOSITORY = "{{< meta manual-repository-url >}}"
  EMPTY_MESSAGE = "Commit history is unavailable in this source checkout."

  module_function

  def git(root, *arguments)
    output, error, status = Open3.capture3("git", "-C", root.to_s, *arguments, binmode: true)
    [output.force_encoding("UTF-8").scrub, error.force_encoding("UTF-8").scrub, status]
  end

  def commits(root, limit: LIMIT, warnings: $stderr)
    raise ArgumentError, "limit must be a positive integer" unless limit.is_a?(Integer) && limit.positive?

    root = Pathname.new(root).realpath
    top, _, status = git(root, "rev-parse", "--show-toplevel")
    # A source archive nested in another repository must not show that repo's log.
    unless status.success? && Pathname.new(top.strip).realpath == root
      warnings.puts "warning: latest changes: no Git checkout; showing the history link only"
      return []
    end

    _, _, status = git(root, "rev-parse", "--verify", "--quiet", "HEAD")
    return [] unless status.success? # Also allow a newly initialized, empty repo.

    shallow, _, status = git(root, "rev-parse", "--is-shallow-repository")
    if status.success? && shallow.strip == "true"
      warnings.puts "warning: latest changes: shallow checkout; run git fetch --unshallow for full history"
    end

    # NUL delimiters keep punctuation in subjects out of the record format.
    output, error, status = git(
      root, "log", "--no-merges", "--date-order", "--max-count=#{limit}",
      "--no-color", "--no-decorate", "--no-notes", "--no-show-signature",
      "--encoding=UTF-8", "--format=%H%x00%cs%x00%s", "-z", "HEAD", "--"
    )
    raise "Cannot read manual commit history: #{error.strip}" unless status.success?

    fields = output.split("\0", -1)
    fields.pop if fields.last == "" # Remove the record terminator, not an empty subject.
    fields.each_slice(3).map do |sha, date, subject|
      unless sha&.match?(/\A[0-9a-f]{40,64}\z/) && date&.match?(/\A\d{4}-\d{2}-\d{2}\z/) && subject
        raise "Unexpected record in manual commit history"
      end
      { sha: sha, date: date, subject: subject }
    end
  rescue Errno::ENOENT
    warnings.puts "warning: latest changes: Git is unavailable; showing the history link only"
    []
  end

  def escape_markdown(text)
    # Escape markup, tables, citations, math and Quarto shortcode delimiters.
    # Preserve the human-readable one-line message, including Unicode.
    text.gsub(/[[:space:]]+/, " ").strip.gsub(/[[:punct:]&&[:ascii:]]/) { |character| "\\#{character}" }
  end

  def markdown(entries)
    lines = ["<!-- Generated by scripts/generate_latest_changes.rb; do not edit. -->", ""]
    if entries.empty?
      lines << EMPTY_MESSAGE
    else
      lines.concat [
        "Recent manual updates from Git commit subjects (newest first; merge commits omitted).",
        "",
        "| Date | Change | Commit |",
        "|:-----------|:------------------------------------------------------|:----------|"
      ]
      entries.each do |entry|
        sha = entry.fetch(:sha)
        lines << "| #{entry.fetch(:date)} | #{escape_markdown(entry.fetch(:subject))} | " \
                 "[`#{sha[0, 7]}`](#{REPOSITORY}/commit/#{sha}) |"
      end
    end
    lines.concat ["", "[View full commit history](#{REPOSITORY}/commits)", ""]
    lines.join("\n")
  end

  def generate(root, limit: LIMIT, warnings: $stderr)
    root = Pathname.new(root).expand_path
    content = markdown(commits(root, limit: limit, warnings: warnings))
    output = root / OUTPUT
    FileUtils.mkdir_p(output.dirname)
    # Do not cause a preview rebuild loop by touching an unchanged include.
    output.write(content, encoding: "UTF-8") unless output.file? && output.read(encoding: "UTF-8") == content
    output
  end
end

if $PROGRAM_NAME == __FILE__
  begin
    LatestChanges.generate(Pathname.new(__dir__).parent)
  rescue StandardError => error
    abort "error: latest changes: #{error.message}"
  end
end
